//------------------------------------------------------------------------------
// <auto-generated>
// WARNING: THIS FILE IS AUTO-GENERATED. DO NOT MODIFY.
// DDS version: 3.13.2
// ACE version: 6.2a_p15
// Running on input file: Test.idl
// </auto-generated>
//------------------------------------------------------------------------------

#pragma once

#include "TestTypeSupportImpl.h"
#include "TestC.h"
#include "marshal.h"

#ifndef EXTERN_METHOD_EXPORT
    #define EXTERN_METHOD_EXPORT extern "C" __declspec(dllexport)
#endif

#ifndef EXTERN_STRUCT_EXPORT
    #define EXTERN_STRUCT_EXPORT extern "C" struct
#endif

/////////////////////////////////////////////////
// TestStruct Declaration
/////////////////////////////////////////////////
EXTERN_STRUCT_EXPORT TestStructWrapper
{
    CORBA::Short ShortField;
    CORBA::UShort UnsignedShortField;
    CORBA::Long LongField;
    CORBA::ULong UnsignedLongField;
    CORBA::LongLong LongLongField;
    CORBA::ULongLong UnsignedLongLongField;

    Test::TestStruct to_native()
    {
        Test::TestStruct ret;

        ret.ShortField = ShortField;
        ret.UnsignedShortField = UnsignedShortField;
        ret.LongField = LongField;
        ret.UnsignedLongField = UnsignedLongField;
        ret.LongLongField = LongLongField;
        ret.UnsignedLongLongField = UnsignedLongLongField;

        return ret;
    }

    void from_native(Test::TestStruct native)
    {
        ShortField = native.ShortField;
        UnsignedShortField = native.UnsignedShortField;
        LongField = native.LongField;
        UnsignedLongField = native.UnsignedLongField;
        LongLongField = native.LongLongField;
        UnsignedLongLongField = native.UnsignedLongLongField;
    }

    void release()
    {
    }

};

EXTERN_METHOD_EXPORT void TestStructWrapper_release(TestStructWrapper* obj);

/////////////////////////////////////////////////
// TestStruct Type Support Methods
/////////////////////////////////////////////////
EXTERN_METHOD_EXPORT Test::TestStructTypeSupport_ptr TestStructTypeSupport_new();

EXTERN_METHOD_EXPORT char* TestStructTypeSupport_GetTypeName(Test::TestStructTypeSupport_ptr native);

EXTERN_METHOD_EXPORT int TestStructTypeSupport_RegisterType(Test::TestStructTypeSupport_ptr native, ::DDS::DomainParticipant_ptr dp, const char* typeName);

EXTERN_METHOD_EXPORT int TestStructTypeSupport_UnregisterType(Test::TestStructTypeSupport_ptr native, ::DDS::DomainParticipant_ptr dp, const char* typeName);

/////////////////////////////////////////////////
// TestStruct DataWriter Methods
/////////////////////////////////////////////////
EXTERN_METHOD_EXPORT Test::TestStructDataWriter_ptr TestStructDataWriter_Narrow(DDS::DataWriter_ptr dw);

EXTERN_METHOD_EXPORT int TestStructDataWriter_Write(Test::TestStructDataWriter_ptr dw, TestStructWrapper* data, int handle);

/////////////////////////////////////////////////
// TestStruct DataReader Methods
/////////////////////////////////////////////////
EXTERN_METHOD_EXPORT Test::TestStructDataReader_ptr TestStructDataReader_Narrow(DDS::DataReader_ptr dr);

EXTERN_METHOD_EXPORT int TestStructDataReader_ReadNextSample(Test::TestStructDataReader_ptr dr, TestStructWrapper* data);

EXTERN_METHOD_EXPORT int TestStructDataReader_Read(Test::TestStructDataReader_ptr dr);
