// -*- C++ -*-
// $Id$

/**
 * Code generated by the The ACE ORB (TAO) IDL Compiler v2.2a_p15
 * TAO and the TAO IDL Compiler have been developed by:
 *       Center for Distributed Object Computing
 *       Washington University
 *       St. Louis, MO
 *       USA
 *       http://www.cs.wustl.edu/~schmidt/doc-center.html
 * and
 *       Distributed Object Computing Laboratory
 *       University of California at Irvine
 *       Irvine, CA
 *       USA
 * and
 *       Institute for Software Integrated Systems
 *       Vanderbilt University
 *       Nashville, TN
 *       USA
 *       http://www.isis.vanderbilt.edu/
 *
 * Information about TAO is available at:
 *     http://www.cs.wustl.edu/~schmidt/TAO.html
 **/

// TAO_IDL - Generated from
// e:\projects\opendds\ext\opendds\ace_wrappers\tao\tao_idl\be\be_codegen.cpp:376


#include "TestPInvokeIdlTypeSupportC.h"
#include "tao/CDR.h"
#include "ace/OS_NS_string.h"

#if !defined (__ACE_INLINE__)
#include "TestPInvokeIdlTypeSupportC.inl"
#endif /* !defined INLINE */

// TAO_IDL - Generated from
// e:\projects\opendds\ext\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Test::BasicTestStructTypeSupport.

Test::BasicTestStructTypeSupport_ptr
TAO::Objref_Traits<Test::BasicTestStructTypeSupport>::duplicate (
    Test::BasicTestStructTypeSupport_ptr p)
{
  return Test::BasicTestStructTypeSupport::_duplicate (p);
}

void
TAO::Objref_Traits<Test::BasicTestStructTypeSupport>::release (
    Test::BasicTestStructTypeSupport_ptr p)
{
  ::CORBA::release (p);
}

Test::BasicTestStructTypeSupport_ptr
TAO::Objref_Traits<Test::BasicTestStructTypeSupport>::nil (void)
{
  return Test::BasicTestStructTypeSupport::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Test::BasicTestStructTypeSupport>::marshal (
    const Test::BasicTestStructTypeSupport_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Test::BasicTestStructTypeSupport::BasicTestStructTypeSupport (void)
{}

Test::BasicTestStructTypeSupport::~BasicTestStructTypeSupport (void)
{
}

Test::BasicTestStructTypeSupport_ptr
Test::BasicTestStructTypeSupport::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return BasicTestStructTypeSupport::_duplicate (
      dynamic_cast<BasicTestStructTypeSupport_ptr> (_tao_objref)
    );
}

Test::BasicTestStructTypeSupport_ptr
Test::BasicTestStructTypeSupport::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return BasicTestStructTypeSupport::_duplicate (
      dynamic_cast<BasicTestStructTypeSupport_ptr> (_tao_objref)
    );
}

Test::BasicTestStructTypeSupport_ptr
Test::BasicTestStructTypeSupport::_nil (void)
{
  return 0;
}

Test::BasicTestStructTypeSupport_ptr
Test::BasicTestStructTypeSupport::_duplicate (BasicTestStructTypeSupport_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Test::BasicTestStructTypeSupport::_tao_release (BasicTestStructTypeSupport_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Test::BasicTestStructTypeSupport::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/TypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Test/BasicTestStructTypeSupport:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Test::BasicTestStructTypeSupport::_interface_repository_id (void) const
{
  return "IDL:Test/BasicTestStructTypeSupport:1.0";
}

::CORBA::Boolean
Test::BasicTestStructTypeSupport::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\projects\opendds\ext\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Test::BasicTestStructDataWriter.

Test::BasicTestStructDataWriter_ptr
TAO::Objref_Traits<Test::BasicTestStructDataWriter>::duplicate (
    Test::BasicTestStructDataWriter_ptr p)
{
  return Test::BasicTestStructDataWriter::_duplicate (p);
}

void
TAO::Objref_Traits<Test::BasicTestStructDataWriter>::release (
    Test::BasicTestStructDataWriter_ptr p)
{
  ::CORBA::release (p);
}

Test::BasicTestStructDataWriter_ptr
TAO::Objref_Traits<Test::BasicTestStructDataWriter>::nil (void)
{
  return Test::BasicTestStructDataWriter::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Test::BasicTestStructDataWriter>::marshal (
    const Test::BasicTestStructDataWriter_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Test::BasicTestStructDataWriter::BasicTestStructDataWriter (void)
{}

Test::BasicTestStructDataWriter::~BasicTestStructDataWriter (void)
{
}

Test::BasicTestStructDataWriter_ptr
Test::BasicTestStructDataWriter::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return BasicTestStructDataWriter::_duplicate (
      dynamic_cast<BasicTestStructDataWriter_ptr> (_tao_objref)
    );
}

Test::BasicTestStructDataWriter_ptr
Test::BasicTestStructDataWriter::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return BasicTestStructDataWriter::_duplicate (
      dynamic_cast<BasicTestStructDataWriter_ptr> (_tao_objref)
    );
}

Test::BasicTestStructDataWriter_ptr
Test::BasicTestStructDataWriter::_nil (void)
{
  return 0;
}

Test::BasicTestStructDataWriter_ptr
Test::BasicTestStructDataWriter::_duplicate (BasicTestStructDataWriter_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Test::BasicTestStructDataWriter::_tao_release (BasicTestStructDataWriter_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Test::BasicTestStructDataWriter::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Test/BasicTestStructDataWriter:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Test::BasicTestStructDataWriter::_interface_repository_id (void) const
{
  return "IDL:Test/BasicTestStructDataWriter:1.0";
}

::CORBA::Boolean
Test::BasicTestStructDataWriter::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

// TAO_IDL - Generated from
// e:\projects\opendds\ext\opendds\ace_wrappers\tao\tao_idl\be\be_visitor_interface\interface_cs.cpp:51

// Traits specializations for Test::BasicTestStructDataReader.

Test::BasicTestStructDataReader_ptr
TAO::Objref_Traits<Test::BasicTestStructDataReader>::duplicate (
    Test::BasicTestStructDataReader_ptr p)
{
  return Test::BasicTestStructDataReader::_duplicate (p);
}

void
TAO::Objref_Traits<Test::BasicTestStructDataReader>::release (
    Test::BasicTestStructDataReader_ptr p)
{
  ::CORBA::release (p);
}

Test::BasicTestStructDataReader_ptr
TAO::Objref_Traits<Test::BasicTestStructDataReader>::nil (void)
{
  return Test::BasicTestStructDataReader::_nil ();
}

::CORBA::Boolean
TAO::Objref_Traits<Test::BasicTestStructDataReader>::marshal (
    const Test::BasicTestStructDataReader_ptr p,
    TAO_OutputCDR & cdr)
{
  return ::CORBA::Object::marshal (p, cdr);
}

Test::BasicTestStructDataReader::BasicTestStructDataReader (void)
{}

Test::BasicTestStructDataReader::~BasicTestStructDataReader (void)
{
}

Test::BasicTestStructDataReader_ptr
Test::BasicTestStructDataReader::_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return BasicTestStructDataReader::_duplicate (
      dynamic_cast<BasicTestStructDataReader_ptr> (_tao_objref)
    );
}

Test::BasicTestStructDataReader_ptr
Test::BasicTestStructDataReader::_unchecked_narrow (
    ::CORBA::Object_ptr _tao_objref)
{
  return BasicTestStructDataReader::_duplicate (
      dynamic_cast<BasicTestStructDataReader_ptr> (_tao_objref)
    );
}

Test::BasicTestStructDataReader_ptr
Test::BasicTestStructDataReader::_nil (void)
{
  return 0;
}

Test::BasicTestStructDataReader_ptr
Test::BasicTestStructDataReader::_duplicate (BasicTestStructDataReader_ptr obj)
{
  if (! ::CORBA::is_nil (obj))
    {
      obj->_add_ref ();
    }
  return obj;
}

void
Test::BasicTestStructDataReader::_tao_release (BasicTestStructDataReader_ptr obj)
{
  ::CORBA::release (obj);
}

::CORBA::Boolean
Test::BasicTestStructDataReader::_is_a (const char *value)
{
  if (
      ACE_OS::strcmp (
          value,
          "IDL:DDS/Entity:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:DDS/DataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:OpenDDS/DCPS/DataReaderEx:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:Test/BasicTestStructDataReader:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/LocalObject:1.0"
        ) == 0 ||
      ACE_OS::strcmp (
          value,
          "IDL:omg.org/CORBA/Object:1.0"
        ) == 0
    )
    {
      return true; // success using local knowledge
    }
  else
    {
      return false;
    }
}

const char* Test::BasicTestStructDataReader::_interface_repository_id (void) const
{
  return "IDL:Test/BasicTestStructDataReader:1.0";
}

::CORBA::Boolean
Test::BasicTestStructDataReader::marshal (TAO_OutputCDR & /* cdr */)
{
  return false;
}

