#include <tao/orb.idl> // Workaround for the error C2961: inconsistent explicit instantiations, a previous explicit instantiation did not specify '__declspec(dllimport)'

module Test {

    #pragma DCPS_DATA_TYPE "Test::NestedTestStruct"    
    struct NestedTestStruct {
        long Id;
        string Message;
    };

    typedef sequence<long> LongList;
    typedef sequence<string> StringList;
    typedef sequence<wstring> WStringList;
    typedef sequence<NestedTestStruct> StructList;
    typedef long ArrayLong[5];
    typedef string ArrayString[10];
    typedef wstring ArrayWString[4];
    typedef NestedTestStruct ArrayStruct[5];
    typedef long MultiArrayLong[3][4][2];
    typedef string MultiArrayString[3][4][2];
    typedef wstring MultiArrayWString[3][4][2];
    typedef NestedTestStruct MultiArrayStruct[3][4][2];

	#pragma DCPS_DATA_TYPE "Test::BasicTestStruct"    
	struct BasicTestStruct {
		long Id;
        string Message;
        wstring WMessage;
        LongList LongSequence;
        StringList StringSequence;
        WStringList WStringSequence;
        ArrayLong LongArray;
        ArrayString StringArray;
        ArrayWString WStringArray;        
        NestedTestStruct StructTest;
        StructList StructSequence;
        ArrayStruct StructArray;
        MultiArrayLong LongMultiArray;
        MultiArrayString StringMultiArray;
        MultiArrayWString WStringMultiArray;
        MultiArrayStruct StructMultiArray;
	};

};
