module Test {

    #pragma DCPS_DATA_TYPE "Test::TestStruct"
    struct TestStruct {
        short ShortField;
        unsigned short UnsignedShortField;
        long LongField;
        unsigned long UnsignedLongField;
        long long LongLongField;
        unsigned long long UnsignedLongLongField;
		char CharField;
		wchar WCharField;
		boolean BooleanField;
		octet OctetField;
		float FloatField;
		double DoubleField;
		long double LongDoubleField;
    };
};
