module Test {

	typedef string<32> BoundedStringType;
	typedef wstring<32> BoundedWStringType;

    #pragma DCPS_DATA_TYPE "Test::TestStruct"
    struct TestStruct {
        short ShortField;
        unsigned short UnsignedShortField;
        long LongField;
        unsigned long UnsignedLongField;
        long long LongLongField;
        unsigned long long UnsignedLongLongField;
		char CharField;
		wchar WCharField;
		boolean BooleanField;
		octet OctetField;
		float FloatField;
		double DoubleField;
		long double LongDoubleField;
		string UnboundedStringField;		
		wstring UnboundedWStringField;
		BoundedStringType BoundedStringField;
		BoundedWStringType BoundedWStringField;
    };
};
