module CdrWrapper {

    typedef sequence<octet> UnboundedOctetSeqType;
    typedef sequence<char> UnboundedCharSeqType;
    typedef sequence<boolean> UnboundedBooleanSeqType;
    typedef sequence<int16> UnboundedInt16SeqType;
    typedef sequence<int32> UnboundedInt32SeqType;
    typedef sequence<int64> UnboundedInt64SeqType;
    typedef sequence<uint16> UnboundedUInt16SeqType;
    typedef sequence<uint32> UnboundedUInt32SeqType;
    typedef sequence<uint64> UnboundedUInt64SeqType;
    typedef sequence<float> UnboundedFloatSeqType;
    typedef sequence<double> UnboundedDoubleSeqType;

    typedef sequence<octet, 5> BoundedOctetSeqType;
    typedef sequence<char, 5> BoundedCharSeqType;
    typedef sequence<boolean, 5> BoundedBooleanSeqType;
    typedef sequence<int16, 5> BoundedInt16SeqType;
    typedef sequence<int32, 5> BoundedInt32SeqType;
    typedef sequence<int64, 5> BoundedInt64SeqType;
    typedef sequence<uint16, 5> BoundedUInt16SeqType;
    typedef sequence<uint32, 5> BoundedUInt32SeqType;
    typedef sequence<uint64, 5> BoundedUInt64SeqType;
    typedef sequence<float, 5> BoundedFloatSeqType;
    typedef sequence<double, 5> BoundedDoubleSeqType;

    typedef char CharArrayType[5];
    typedef boolean BooleanArrayType[5];
    typedef octet OctetArrayType[5];
    typedef short Int16ArrayType[5];
    typedef unsigned short UInt16ArrayType[5];
    typedef long Int32ArrayType[5];
    typedef unsigned long UInt32ArrayType[5];
    typedef long long Int64ArrayType[5];
    typedef unsigned long long UInt64ArrayType[5];
    typedef float FloatArrayType[5];
    typedef double DoubleArrayType[5];

    typedef sequence<octet, 2048> OctetSequenceType;

    @topic
    struct TestPrimitive {
        boolean BoolField;
        octet ByteField;
        int16 Int16Field;
        int32 Int32Field;
        int64 Int64Field;
        uint16 UInt16Field;
        uint32 UInt32Field;
        uint64 UInt64Field;
        float FloatField;
        double DoubleField;
        char CharField;
    };

    @topic
    struct TestPrimitiveSequence {
        UnboundedBooleanSeqType UnboundedBooleanSequenceField;
        UnboundedOctetSeqType UnboundedByteSequenceField;
        UnboundedInt16SeqType UnboundedInt16SequenceField;
        UnboundedInt32SeqType UnboundedInt32SequenceField;
        UnboundedInt64SeqType UnboundedInt64SequenceField;
        UnboundedUInt16SeqType UnboundedUInt16SequenceField;
        UnboundedUInt32SeqType UnboundedUInt32SequenceField;
        UnboundedUInt64SeqType UnboundedUInt64SequenceField;
        UnboundedFloatSeqType UnboundedFloatSequenceField;
        UnboundedDoubleSeqType UnboundedDoubleSequenceField;
        UnboundedCharSeqType UnboundedCharSequenceField;

        BoundedBooleanSeqType BoundedBooleanSequenceField;
        BoundedOctetSeqType BoundedByteSequenceField;
        BoundedInt16SeqType BoundedInt16SequenceField;
        BoundedInt32SeqType BoundedInt32SequenceField;
        BoundedInt64SeqType BoundedInt64SequenceField;
        BoundedUInt16SeqType BoundedUInt16SequenceField;
        BoundedUInt32SeqType BoundedUInt32SequenceField;
        BoundedUInt64SeqType BoundedUInt64SequenceField;
        BoundedFloatSeqType BoundedFloatSequenceField;
        BoundedDoubleSeqType BoundedDoubleSequenceField;
        BoundedCharSeqType BoundedCharSequenceField;
    };

    @topic
    struct TestPrimitiveArray {
        BooleanArrayType BooleanArrayField;
        OctetArrayType ByteArrayField;
        Int16ArrayType Int16ArrayField;
        Int32ArrayType Int32ArrayField;
        Int64ArrayType Int64ArrayField;
        UInt16ArrayType UInt16ArrayField;
        UInt32ArrayType UInt32ArrayField;
        UInt64ArrayType UInt64ArrayField;
        FloatArrayType FloatArrayField;
        DoubleArrayType DoubleArrayField;
        CharArrayType CharArrayField;
    };

    @topic
    struct KeyedOctets {
        @key string<1024> KeyField;
        OctetSequenceType ValueField;
    };
};
