module CdrWrapper {

    @topic
    struct TestPrimitive {
        boolean BoolField;
        octet ByteField;
        int16 Int16Field;
        int32 Int32Field;
        int64 Int64Field;
        uint16 UInt16Field;
        uint32 UInt32Field;
        uint64 UInt64Field;
        float FloatField;
        double DoubleField;
        char CharField;
//        wchar WCharField;
    };
};
