name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:        
        BuildPlatform: [x64, x86]
        BuildConfiguration: [Release, Debug]
        
    steps:
    - uses: actions/checkout@v1

    - name: Build & Test with Cake
      shell: pwsh
      run: ${{ github.workspace }}/Build/OpenDDSharp.Build.CppCli.ps1 --BuildConfiguration=${{ matrix.BuildConfiguration }} --BuildPlatform=${{ matrix.BuildPlatform }} --VisualStudioVersion=VS2019
      working-directory: ${{ github.workspace }}/Build
