name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: windows-2019
    strategy:
      matrix:        
        BuildPlatform: [x64, x86]
        BuildConfiguration: [Release, Debug]
    env:
      OpenDdsVersion: "3.14.1"
        
    steps:
    - uses: actions/checkout@v2

    - name: Cache OpenDDS libraries
      id: opendds-libraries
      uses: actions/cache@v2
      with:
        path: |          
          '${{ github.workspace }}\ext\OpenDDS\lib_${{ matrix.BuildPlatform }}\*.dll'
          '${{ github.workspace }}\ext\OpenDDS\lib_${{ matrix.BuildPlatform }}\*.lib'
          '${{ github.workspace }}\ext\OpenDDS\bin_${{ matrix.BuildPlatform }}'
          '${{ github.workspace }}\ext\OpenDDS\dds\idl\IDLTemplate.txt'
          '${{ github.workspace }}\ext\OpenDDS\ACE_TAO\ACE\lib_${{ matrix.BuildPlatform }}\*.dll'
          '${{ github.workspace }}\ext\OpenDDS\ACE_TAO\ACE\lib_${{ matrix.BuildPlatform }}\*.lib'         
          '${{ github.workspace }}\ext\OpenDDS\ACE_TAO\ACE\bin_${{ matrix.BuildPlatform }}'
          '${{ github.workspace }}\ext\OpenDDS\dds\**\*.h'
          '${{ github.workspace }}\ext\OpenDDS\dds\**\*.cpp'
          '${{ github.workspace }}\ext\OpenDDS\dds\**\*.inl'
          '${{ github.workspace }}\ext\OpenDDS\dds\**\*.idl'
          '${{ github.workspace }}\ext\OpenDDS\dds\**\*.pidl'
          '${{ github.workspace }}\ext\ACE_TAO\ACE\ace\**\*.h'
          '${{ github.workspace }}\ext\ACE_TAO\ACE\ace\**\*.inl'
          '${{ github.workspace }}\ext\ACE_TAO\ACE\ace\**\*.cpp'
          '${{ github.workspace }}\ext\ACE_TAO\TAO\tao\**\*.h'
          '${{ github.workspace }}\ext\ACE_TAO\TAO\tao\**\*.inl'
          '${{ github.workspace }}\ext\ACE_TAO\TAO\tao\**\*.cpp'
          '${{ github.workspace }}\ext\ACE_TAO\TAO\tao\**\*.idl'
          '${{ github.workspace }}\ext\ACE_TAO\TAO\tao\**\*.pidl'
        key: opendds-cache-${{ env.OpenDdsVersion }}-${{ matrix.BuildConfiguration }}-${{ matrix.BuildPlatform }}-2

    - name: Build & Test with Cake (OpenDDS cache found)
      shell: pwsh
      if: steps.opendds-libraries.outputs.cache-hit == 'true'
      run: ${{ github.workspace }}/Build/OpenDDSharp.Build.CppCli.ps1 --BuildConfiguration=${{ matrix.BuildConfiguration }} --BuildPlatform=${{ matrix.BuildPlatform }} --OpenDdsVersion=${{ env.OpenDdsVersion }} --IgnoreThirdPartySetup
      working-directory: ${{ github.workspace }}/Build

    - name: Build & Test with Cake (OpenDDS cache not found)
      shell: pwsh
      if: steps.opendds-libraries.outputs.cache-hit != 'true'
      run: ${{ github.workspace }}/Build/OpenDDSharp.Build.CppCli.ps1 --BuildConfiguration=${{ matrix.BuildConfiguration }} --BuildPlatform=${{ matrix.BuildPlatform }} --OpenDdsVersion=${{ env.OpenDdsVersion }}
      working-directory: ${{ github.workspace }}/Build
