name: Continuous Integration

on:
  push:
  schedule:
    - cron: '0 1 * * SUN'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: windows-2019
    strategy:
      fail-fast: false
      matrix:        
        BuildPlatform: [x64, x86]
        BuildConfiguration: [Release, Debug]
        OpenDdsVersion: ["3.18.1"]
    steps:
    - uses: actions/checkout@v2

    - name: Cache OpenDDS libraries
      id: opendds-libraries
      uses: actions/cache@v2
      with:
        path: |          
          ${{ github.workspace }}/ext/OpenDDS/**/*.dll
          ${{ github.workspace }}/ext/OpenDDS/**/*.lib
          ${{ github.workspace }}/ext/OpenDDS/**/*.exe
          ${{ github.workspace }}/ext/OpenDDS/dds/idl/IDLTemplate.txt
          ${{ github.workspace }}/ext/OpenDDS/**/*.h
          ${{ github.workspace }}/ext/OpenDDS/**/*.hpp
          ${{ github.workspace }}/ext/OpenDDS/**/*.cpp
          ${{ github.workspace }}/ext/OpenDDS/**/*.inl
          ${{ github.workspace }}/ext/OpenDDS/**/*.idl
          ${{ github.workspace }}/ext/OpenDDS/**/*.pidl
        key: opendds-cache-${{ matrix.OpenDdsVersion }}-${{ matrix.BuildConfiguration }}-${{ matrix.BuildPlatform }}

    - name: Build & Test with Cake (No cached)
      shell: pwsh
      if: steps.opendds-libraries.outputs.cache-hit != 'true'
      run: ${{ github.workspace }}/Build/OpenDDSharp.Build.CppCli.ps1 --BuildConfiguration=${{ matrix.BuildConfiguration }} --BuildPlatform=${{ matrix.BuildPlatform }} --OpenDdsVersion=${{ matrix.OpenDdsVersion }} --IgnoreThirdPartySetup=False
      working-directory: ${{ github.workspace }}/Build
      
    - name: Build & Test with Cake (Cached)
      shell: pwsh
      if: steps.opendds-libraries.outputs.cache-hit == 'true'
      run: ${{ github.workspace }}/Build/OpenDDSharp.Build.CppCli.ps1 --BuildConfiguration=${{ matrix.BuildConfiguration }} --BuildPlatform=${{ matrix.BuildPlatform }} --OpenDdsVersion=${{ matrix.OpenDdsVersion }} --IgnoreThirdPartySetup=True
      working-directory: ${{ github.workspace }}/Build
