name: CI

on: [push]

jobs:
  build:

    runs-on: windows-2019

    strategy:
      matrix:        
        BuildPlatform: [x64, x86]
        BuildConfiguration: [Release, Debug]
        
    steps:
    - uses: actions/checkout@v1

    - name: Run a one-line script
      shell: pwsh
      run: ./Build/OpenDDSharp.Build.CppCli.ps1 --BuildConfiguration=$(BuildConfiguration) --BuildPlatform=$(BuildPlatform) --VisualStudioVersion=VS2019
      working-directory: ./Build
