module Test {
	enum PrimitiveEnum {
		ENUM1,
		ENUM2,
		ENUM3
	};

    enum SupportTestKind {
        InconsistentTopicTest
    };

	#pragma DCPS_DATA_TYPE "Test::BasicTestStruct"    
	struct BasicTestStruct {
		long Id;
	};

    typedef sequence<long, 20> LongList;
	typedef sequence<string> StringList;
	typedef sequence<BasicTestStruct, 20> StructList;	
	typedef sequence<long double> LongDoubleList;
    typedef long ArrayLong[3][4];
	typedef string ArrayString[2][2];
	typedef BasicTestStruct ArrayStruct[2][2];
	typedef long double ArrayLongDouble[2][2];
	typedef long TestPrimitiveTypedef;

    const long TEST_CONST = 1;
	const string TEST_STRING_CONST = "Hello, I love you, won't you tell me your name?";
    
	#pragma DCPS_DATA_TYPE "Test::TestStruct"
	#pragma DCPS_DATA_KEY "Test::TestStruct Id"
    struct TestStruct {
		long Id;
		string RawData;
		long long TimeTicks;
        char CharType;
        wchar WcharType;
        octet OctetType;
        short ShortType;
        unsigned short UnsignedShortType;
        unsigned long UnsignedLongType;
        unsigned long long UnsignedLongLongType;
        float FloatType;
        double DoubleType;
        long double LongDoubleType;
        boolean BooleanType; 
        wstring WstringType; 		
        LongList LongSequence;  
		StringList StringSequence;	
		StructList StructSequence;
		LongDoubleList LongDoubleSequence;
        ArrayLong LongArray;
		ArrayString StringArray;
		ArrayStruct StructArray;
		ArrayLongDouble LongDoubleArray;
		BasicTestStruct StructTest;		
        PrimitiveEnum TestEnum;
	};

	#pragma DCPS_DATA_TYPE "Test::Athlete"    
	#pragma DCPS_DATA_KEY "Test::Athlete AthleteId"
	struct Athlete
	{
		long AthleteId;
		string FirstName;
		string SecondName;
		string Country;
	};

	#pragma DCPS_DATA_TYPE "Test::Result"
	#pragma DCPS_DATA_KEY "Test::Result AthleteId"
	struct Result
	{				
		long AthleteId;
		long Rank;
		float Score;		
	};

	#pragma DCPS_DATA_TYPE "Test::AthleteResult"    
	#pragma DCPS_DATA_KEY "Test::AthleteResult AthleteId"
	struct AthleteResult
	{
		long AthleteId;
		string FirstName;
		string SecondName;
		string Country;
		long Rank;
		float Score;
	};
};
